import Layout from '@/components/Layout'
import '../../style/globals.css'

export const metadata = {
  title: 'Cafshane',
  description: 'Generated by create next app',
  icons: {
    icon: 'images/HeaderLogo.png',
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  )
}
